### ISSUE TITLE
 It won't start on Windows 11.

### ISSUE THREAD

**Issue by Rakkyotan** [w-okada/ttsclient#2]
Thank you as always.
We request support for Windows 11.
All my computers at home are Windows 11...

----
C:\TTS0118>main.exe cui --https false --no_cui True
python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
MEIPASS: C:\TTS0118\_internal
checking the modules...

module download fin!

                       tts client

----------------------------------------------------------
 Application | http://localhost:19000
 Log(rich)   | http://localhost:19000/?app_mode=LogViewer
 Log(text)   | http://localhost:19000/vcclient.log
 API         | http://localhost:19000/docs
 License(js) | http://localhost:19000/licenses-js.json
 License(py) | http://localhost:19000/licenses-py.json
----------------------------------------------------------
Please press Ctrl+C once to exit vcclient.
onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.

**Comment by w-okada** [comment]
Access with browser http://localhost:19000

ttsclient doesn't include client gui.

**Comment by Rakkyotan** [comment]
It's done! thank you

**Comment by kazumi371** [comment]
add rvc
